### ISSUE TITLE
Move app wide settings out of preferences

### ISSUE THREAD

**Issue by lukechilds** [atomiclabs/hyperdex#217]
Things like setting a custom `marketmaker` daemon url or netid/seednode should be done before login.

We should move these and any other app wide settings to the login view. Preferably hidden behind a cog button or something so we don't clutter the login.

We should probably then move all settings in the preferences section into the portfolio file so they are portfolio specific.

Related: https://github.com/lukechilds/hyperdex/issues/216

**Comment by sindresorhus** [comment]
> We should move these and any other app wide settings to the login view. Preferably hidden behind a cog button or something so we don't clutter the login.

Or just use the `Preferences…` menu item:

<img width="304" alt="screen shot 2018-05-14 at 18 45 35" src="https://user-images.githubusercontent.com/170270/39995619-04c3244e-57a7-11e8-8045-56e0d13cc788.png">

**Comment by lukechilds** [comment]
>Or just use the Preferences… menu item:

Yeah, good point.
