### ISSUE TITLE
Export the trading history to Excel 

### ISSUE THREAD

**Issue by ip-config** [atomiclabs/hyperdex#241]
Hello,
just another idea about Export the trading history to excel, will be perfect ^^'

---

HyperDEX Nightly 0.0.0-a36030c-18.5.19.1359
Electron 2.0.1
win32 10.0.16299
Locale: en-US

**Comment by sindresorhus** [comment]
Can you give us some insight into why you need it and what you would use the Excel file for?

**Comment by ip-config** [comment]
Hello,
Sure,
1>>Exportation to Excel csv or xml Data For help/better for backtest Tracking, for future trade/swap strategy's.
2>>History of trading/swaps in Hyperdex, when install new desktop trading history should be saved in old one (Localhost), so users of hyperdex need to backup or save swaps/trading history.
3>>Sharing history.
4>>Using the Data for generate reports with more charts and advance tools.
Regards

**Comment by sindresorhus** [comment]
I think this could be useful for many.

@atomiclabs/core Thoughts?

**Comment by kevva** [comment]
> @atomiclabs/core Thoughts?

Yes, I was about to bring this up too. Keeping statistics over your trades is very useful. It's especially useful to be able to export the data since most people use more than one exchange.

**Comment by sindresorhus** [comment]
I don't think we're ready to commit to export/import of JSON, but I'll work on the CSV export tomorrow.

**Comment by sindresorhus** [comment]
> when install new desktop trading history should be saved in old one (Localhost), so users of hyperdex need to backup or save swaps/trading history.

I've moved this to a new issue https://github.com/atomiclabs/hyperdex/issues/454
