### ISSUE TITLE
Missing cryptocurrency icons

### ISSUE THREAD

**Issue by sindresorhus** [atomiclabs/hyperdex#248]
We need icons for these currencies:

- [x] ARG: https://github.com/atomiclabs/cryptocurrency-icons/issues/188
- [x] BCBC: I've emailed them. If they don't answer, we can vectorize [the PNG](https://cleanblockchain.org/images/bcbc.png).
- [x] BTCH: https://github.com/atomiclabs/cryptocurrency-icons/issues/197
- [x] COQUI: https://github.com/cjdowner/cryptocurrency-icons/issues/111
- [x] FJC: https://github.com/atomiclabs/cryptocurrency-icons/issues/189
- [x] HODL: https://github.com/HOdlcoin/HOdlcoin/issues/130 https://github.com/cjdowner/cryptocurrency-icons/issues/112
- [x] OOT: https://github.com/cjdowner/cryptocurrency-icons/issues/107
- [x] SIB: https://github.com/atomiclabs/cryptocurrency-icons/issues/190
- [x] XSG: https://github.com/atomiclabs/cryptocurrency-icons/issues/191
- [x] MNZ: https://github.com/cjdowner/cryptocurrency-icons/issues/113
- [x] RAP: https://github.com/atomiclabs/cryptocurrency-icons/issues/192
- [x] PAC: https://github.com/atomiclabs/cryptocurrency-icons/issues/193
- [x] GLXT: https://github.com/hyperdexapp/cryptocurrency-icons/issues/148
- [x] CC: https://github.com/atomiclabs/cryptocurrency-icons/issues/203
- [x] XMCC: https://github.com/atomiclabs/cryptocurrency-icons/issues/204
- [x] POLIS: https://github.com/atomiclabs/cryptocurrency-icons/issues/205
- [x] STAK: https://github.com/atomiclabs/cryptocurrency-icons/issues/208
- [ ] CHAIN: https://github.com/atomiclabs/cryptocurrency-icons/issues/232

We are planning to make our own icons for:

- [x] BOTS
- [x] CRYPTO
- [x] DEX (InstantDEX)
- [x] JUMBLR
- [x] KV
- [x] MSHARK
- [x] PANGEA
- [x] REVS
- [x] SUPERNET
- [x] WLC

We're using https://github.com/cjdowner/cryptocurrency-icons, so we need to open issues there with the source graphics (meaning the original design files, not `png` or `jpg` files). Only open a new issue there if you can also provide the source files. One issue per currency.

We need help finding the source graphics and opening issues.

**Comment by leto** [comment]
FYI Snowgem has changed their ticker symbol from SNG to XSG

**Comment by sindresorhus** [comment]
@siulynot Could you share the Chainmaker logo source file? We would like to make an icon for it for HyperDEX.

**Comment by siulynot** [comment]
yes
![symbol](https://user-images.githubusercontent.com/225342/47309469-7e2da780-d602-11e8-993d-4aecd66bfce1.png)
![logotype](https://user-images.githubusercontent.com/225342/47309471-7e2da780-d602-11e8-9f85-02360bb6e91d.png)

**Comment by siulynot** [comment]
ok

**Comment by siulynot** [comment]
ok

[Chainmakers Logo_SVG.svg.zip](https://github.com/atomiclabs/hyperdex/files/2506205/Chainmakers.Logo_SVG.svg.zip)

**Comment by leto** [comment]
@sindresorhus it looks like you have what you need for BTCH, let us know what else you might need

**Comment by sindresorhus** [comment]
@siulynot Thanks :) https://github.com/atomiclabs/cryptocurrency-icons/issues/232

**Comment by sindresorhus** [comment]
@leto Yes, it's done in https://github.com/atomiclabs/cryptocurrency-icons/pull/226. Just waiting for it to be done and merged.
