### ISSUE TITLE
Got `Error Code: -1002` when swapping

### ISSUE THREAD

**Issue by Erlix322** [atomiclabs/hyperdex#253]
Got this message when trying to swap!

Error Code: -1002
![swaperror](https://user-images.githubusercontent.com/16254580/40318721-dc46cc26-5d25-11e8-9052-77688a0d96c5.png)

HyperDEX 0.1.0-alpha.1
Electron 2.0.0
win32 10.0.16299
Locale: de

**Comment by sindresorhus** [comment]
We, unfortunately, don't know what all the error codes mean. We get them from the underlaying daemon we use called `marketmaker`.

I've added your error to our list of errors to investigate: https://docs.google.com/spreadsheets/d/1blgmrJCZ-SfYaJdTTVdk717kZ43R4yzm9YIW2Bt--EM/edit#gid=0

We plan to add better error messages in the future.

**Comment by sindresorhus** [comment]
Closing this in favor of https://github.com/atomiclabs/hyperdex/issues/180
