### ISSUE TITLE
Crash clicking on View button

### ISSUE THREAD

**Issue by barbierir** [atomiclabs/hyperdex#265]
OS: Ubuntu 18.04 with HyperDex .deb installer
Issue: after an "unmatched" trade I clicked on the "View" button and the app crashed. Cli shows the following message: 

>  mm › sh: 1: curl: not found

---

HyperDEX 0.1.0-alpha.1
Electron 2.0.0
linux 4.15.0-20-generic
Locale: it

**Comment by lukechilds** [comment]
Looks like an issue with `marketmaker`, unrelated to the GUI.

Do you have `curl` installed?

cc @jl777

**Comment by sindresorhus** [comment]
> Do you have curl installed?

@barbierir :arrow_up:

**Comment by barbierir** [comment]
No, I just installed it. Anyway I checked the latest release and it works fine, the crash doesn't happen

**Comment by sindresorhus** [comment]
Ok. Thanks for letting us know :)
