### ISSUE TITLE
BEER for PIZZA

### ISSUE THREAD

**Issue by cbowman596** [atomiclabs/hyperdex#272]
The attached screenshot displays:

Requested
Buy: 1 PIZZA
For: 9999.xx BEER
Price: 9999.xx BEER

Should it display as:

Requested
Buy: 9999.xx PIZZA
For: 1 BEER
Price: 1 BEER

![image](https://user-images.githubusercontent.com/1307577/40332570-0f948a5c-5d1a-11e8-95ed-9d602b0cd719.png)

---

HyperDEX 0.1.0-alpha.1
Electron 2.0.0
win32 6.1.7601
Locale: en-US

**Comment by sindresorhus** [comment]
This was fixed by https://github.com/atomiclabs/hyperdex/pull/358
