### ISSUE TITLE
swapstatus(requestid,quoteid) calling hourly on unfinished swaps

### ISSUE THREAD

**Issue by CHMEX** [atomiclabs/hyperdex#310]
Suggestions from testing.

jl777 [1:56 PM]
marketmaker is doing swapstatus in the background so likely it would also have automatically reclaimed given time

CHMEX [2:02 PM]
I did one LTC / KMD swap on hyperdex (alice).
alice paid the payment but did not receive the LTC. This was 24 hours ago. I now executed below from console
curl --url "http://127.0.0.1:7783" --data "{\"userpass\":\"$userpass\",\"method\":\"swapstatus\",\"requestid\":3088094260,\"quoteid\":4160281382}"
manualy and I received my KMD alice payment back kmdexplorer.ru/tx/9939a46b2fbbc8c92914e6fd7e1f7daa331c602660cbd14a0177eca4f369f312
This is a windows expierence

jl777 [2:04 PM]
you shouldnt have to do anything special... it would be good for the GUI to make sure the swapstatus(requestid,quoteid) is called hourly on unfinished swaps

slackbot [2:06 PM]
Your file was uploaded — it’s safe and sound in Slack. Unfortunately your workspace doesn’t have any storage space left. To get more space, you can upgrade to a paid account or delete some of your older files.

CHMEX [2:06 PM]
![image](https://user-images.githubusercontent.com/33424502/40484419-d6b6acd0-5f5b-11e8-81d2-c89507c28e2b.png)

@lukechilds fyi this is how it looked in the gui let me know if you need info I will put the whole thing on github for your reference

---

HyperDEX Nightly 0.0.0-adff629-18.5.17.713
Electron 2.0.1
win32 10.0.16299
Locale: en-US

**Comment by jorian** [comment]
mm2.0 has this already integrated.
