### ISSUE TITLE
UTXO explanation link to stackexchange answer in welcome popup

### ISSUE THREAD

**Issue by gcharang** [atomiclabs/hyperdex#312]
Hi! the answer in the stackexchange link while explaining inputs and outputs also introduces change addresses, which might confuse HyperDEX users who will have a single address per coin per seed. The following links might be better resources.

https://www.youtube.com/watch?v=yALgq6s3t9A
https://allthingscrypto.tech/the-importance-of-the-concept-of-utxo-for-komodo-and-barterdex/
https://medium.com/@satindergrewal/barterdex-tips-tricks-a26e230603b1
https://untoldd.com/komodotest/2018/03/24/what-is-utxos/
---

HyperDEX Nightly 0.0.0-e08a542-18.5.23.1401
Electron 2.0.2
linux 4.13.0-43-generic
Locale: en-GB

**Comment by lukechilds** [comment]
Thanks for the suggestion, yeah I agree, those links were picked via a quick Google to make it into the first alpha release.

I'm not totally sold on those links, we need something written in good english and I think including the one with the BarterDEX GUI might be a little confusing.

The link should be purely about what UTXOs are, without going into too much detail about how they're used in HyperDEX, that would belong on a separate page.

Feel free to post any more UTXO links you find but I think we might leave it as is during the alpha phase and write some of our own content for the public release.

**Comment by gcharang** [comment]
https://docs.komodoplatform.com/whitepaper/chapter6.html#the-utxo-an-elusive-yet-fundamental-concept

This part of the whitepaper has a very comprehensive introduction.

**Comment by lukechilds** [comment]
Thanks, that's a great resource 👍

**Comment by jorian** [comment]
UTXO management is not needed as of mm2.0
