### ISSUE TITLE
The decimal point is displayed as text

### ISSUE THREAD

**Issue by VONLUEAPS** [atomiclabs/hyperdex#318]
![image](https://user-images.githubusercontent.com/16932261/40557781-3b49b06c-608c-11e8-8899-fd30d9cd0027.png)

Step :
1. Input purchase price is 0.00250835BCH.
2. Click the Max button to enter the maximum quantity.
3. Check Total (BCH):

- I think it should be displayed as 0.0000002 instead of 2e-7.

HyperDEX 0.1.0-alpha.1
Electron 2.0.0
win32 10.0.17134
Locale: ko

**Comment by sindresorhus** [comment]
I agree. I'm already working on a fix for this, I just didn't have time to finish it for this release.
