### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by ip-config** [atomiclabs/hyperdex#320]
Hey
i get this error when i click on settings:  
> Unhandled Promise Rejection
> TypeError: Cannot read property 'value' of undefined
>     at currencyHistoryFirstValue.map (app://-/bundle.js:2262:41)
>     at Array.map (<anonymous>)
>     at DashboardContainer.calculatePortfolioPriceHistory (app://-/bundle.js:2256:45)
>     at app://-/bundle.js:2337:33
>     at Generator.next (<anonymous>)
>     at step (app://-/bundle.js:2093:191)
>     at app://-/bundle.js:2093:361
>     at <anonymous>

![image](https://user-images.githubusercontent.com/12597726/40570090-84d31a98-6087-11e8-992f-d0dce7360be4.png)

thanks

---

HyperDEX 0.1.0-alpha.2
Electron 2.0.2
win32 10.0.16299
Locale: en-US

**Comment by sindresorhus** [comment]
@ip-config Can you confirm whether this is still an issue in the latest alpha version? https://github.com/atomiclabs/hyperdex/releases/latest
