### ISSUE TITLE
More portfolio settings

### ISSUE THREAD

**Issue by sindresorhus** [atomiclabs/hyperdex#359]
- [ ] Ability to rename the portfolio.
- [ ] "Delete portfolio" button, with big red confirmation modal (!).
- [ ] "View seed phrase" button. Click it, get a modal with password prompt before showing the seed phrase.

**Comment by kevva** [comment]
Maybe we should enforce entering the seed phrase when removing a portfolio?

**Comment by lukechilds** [comment]
Good idea I like it.

Btw, the way the auth works, the suer never enters the seed phrase (unless they are restoring a portfolio). We encrypt the seed on disk with the user's password. So we don't know the seed phrase without the password so we have nothing to compare against.

We do have authentication on the decryption though. So we should ask for the password, attempt to decrypt their seed, if it throws, they used in incorrect password, so we don't allow deletion.

Alternatively maybe we should enforce entering the portfolio name, GitHub style. That way they won't accidentally delete the wrong repo.

Or both.

**Comment by kevva** [comment]
> Alternatively maybe we should enforce entering the portfolio name, GitHub style. That way they won't accidentally delete the wrong repo.

I went with that for now, but I'm open to changing it. https://github.com/hyperdexapp/hyperdex/pull/407

**Comment by lukechilds** [comment]
@sindresorhus @kevva is this resolved now with https://github.com/atomiclabs/hyperdex/pull/407?

**Comment by sindresorhus** [comment]
Yup
