### ISSUE TITLE
Enhancement - Delete swap history

### ISSUE THREAD

**Issue by jdmarlow86** [atomiclabs/hyperdex#366]
When the new delete swap history option is selected the app is closed and returns to the login screen without warning. If the restart is by design I suggest adding a message of sorts after selecting the option. If the restart isn't by design then I suggest a simple "Swaps deleted" message without a restart

**Comment by sindresorhus** [comment]
The `Debug` menu is just meant for us and when we need to debug something with testers. It will not be visible in the public launch version, so spending time on making it user-friendly is a non-goal. We have to do the restart to ensure the state doesn't go out of sync.

Instead, we'll add some more user-friendly buttons to achieve the same thing in the UI: https://github.com/atomiclabs/hyperdex/issues/423
