### ISSUE TITLE
App navigation error

### ISSUE THREAD

**Issue by jdmarlow86** [atomiclabs/hyperdex#376]
1. After login select Settings
2. Select Logout link under App Settings
3. Select Portfolio -> any option (Exchange, Trades, etc)
4. Receive the below error and the screen goes blank

![image](https://user-images.githubusercontent.com/22251770/41815345-15104c6a-7736-11e8-8a47-f0120afb8382.png)
![image](https://user-images.githubusercontent.com/22251770/41815350-2202fe86-7736-11e8-946a-25308a9f58a4.png)

Version: alpha 7
OS: windows 10
Errors: above
Severity: Medium (Sev 2)

**Comment by sindresorhus** [comment]
This is an oversight. The `Portfolio` menu should not be visible when logged out. Thanks for reporting.
