### ISSUE TITLE
"Add Currencies" button in the Dashboard 

### ISSUE THREAD

**Issue by sindresorhus** [atomiclabs/hyperdex#425]
Would be useful to show this if the user has not yet added/remove any currencies, so to encourage them to add some more. Clicking the button would take them to the Settings view.

We can detect that the list of currencies is the same as the default. But what happens the user adds some coins and then removes them so it's back to the default. We wouldn't want to show the button again then. So maybe we should persist if the list of currencies has been edited once? // @atomiclabs/core

**Comment by lukechilds** [comment]
Yeah, I like that, they could mistakenly think the defaults are the only ones we support if they haven't seen the settings view.

We could add a `hasChangedCurrencies` boolean to the config.

**Comment by kevva** [comment]
Where should it be placed?

**Comment by lukechilds** [comment]
One idea could be to add a plus button next to the currency search, something like this:

![screen shot 2018-07-26 at 2 51 26 pm](https://user-images.githubusercontent.com/2123375/43267309-81daabc4-90e5-11e8-9c3e-7bf0e07dfde7.png)

Note sure if that's clear enough.

**Comment by kevva** [comment]
I'm not a designer, but I like it. Maybe add a tooltip for it?

**Comment by lukechilds** [comment]
Me neither haha, could definitely do with some more clarity, tooltip would help.

**Comment by lukechilds** [comment]
In fact, come to think of it, I'm not sure it makes sense to have add/remove currencies in the settings at all.

It would make way more sense to have it all in the dashboard. So you can remove any of those currencies in the list by clicking an X or whatever. Then Clicking the plus would bring up some groovy modal or something to add a new one.

I don't see any reason to separate this process out to a different view.

That would obvs be a fairly big change so no need to do it before launch, but if others agree we could refactor to that at a later point.

**Comment by sindresorhus** [comment]
I prefer to put uncommon actions in a separate Settings view to reduce UI clutter. The idea here was to just show the user they can add currencies, not to add a permanent `+` button.

> So you can remove any of those currencies in the list by clicking an X or whatever.

Not sure we should clutter the UI with edit control for actions you don't do very often. It's not like you remove and add currencies every day.

**Comment by sindresorhus** [comment]
I was thinking something like this (rough mockup):

![screen shot 2018-07-31 at 14 15 23](https://user-images.githubusercontent.com/170270/43443831-3783bdd2-94cc-11e8-8a63-dc34a198b17c.png)
