### ISSUE TITLE
Hyperdex Alpha new version

### ISSUE THREAD

**Issue by 101Catalyst** [atomiclabs/hyperdex#427]
Well i downloaded the new Alpha version of the hyperdex, installed it, made a new account, signed in.
It now stuck on the Thank you for helping test hyperdex. 
I tried to do random clicks to let this message go, clicked the X mark. nothing happens. Had restarted it twice nothing happens never goes past that message.
Windows 10 pro 

---

HyperDEX 0.1.0-alpha.10
Electron 2.0.4
win32 10.0.10240
Locale: en-US

**Comment by sindresorhus** [comment]
Sorry about that. We had a slight issue with the latest builds. I've uploaded fixed builds now: https://github.com/atomiclabs/hyperdex/releases/tag/v0.1.0-alpha.10 (You need to download it again).
