### ISSUE TITLE
View Seed Phrase Error

### ISSUE THREAD

**Issue by jdmarlow86** [atomiclabs/hyperdex#429]
After entering an incorrect password I receive the below error. Reproduced it consistently

Version: alpha 10
OS: win
Errors: below
Severity: Medium (2)

![image](https://user-images.githubusercontent.com/22251770/42850695-d08ffc56-89f6-11e8-91cc-53a6c0756be9.png)

**Comment by sindresorhus** [comment]
Confirmed. Thanks for reporting.
