### ISSUE TITLE
Bug: Enter your seed window moves cursor position

### ISSUE THREAD

**Issue by 1mk3r** [atomiclabs/hyperdex#432]
"Enter your seed" form moves cursor position to the end of the text after any typing.
For example i typing: "125", after that, i moving cursor in position after 2 - "12|5", after that i typing 3 and 4, but i see 12354 instead of 12345 because cursor moves to the end position of text after any typing. 
Please change it, beacause i cant type mnemonical passwords in this way.

**Comment by sindresorhus** [comment]
Confirmed. I checked and this regression was introduced in https://github.com/atomiclabs/hyperdex/commit/33c4cef236fa9f24f8ddff16cc81f16ee16739eb.
