### ISSUE TITLE
Add PropTypes to all the reusable components

### ISSUE THREAD

**Issue by sindresorhus** [atomiclabs/hyperdex#435]
To prevent silly mistakes.

Components: https://github.com/atomiclabs/hyperdex/tree/master/app/renderer/components

**Comment by joao-alberto** [comment]
Can I help with that?

**Comment by lukechilds** [comment]
@joao-alberto Of course, that would be very much appreciated!

**Comment by joao-alberto** [comment]
@lukechilds Thanks! I will work on it today or tomorrow.
