### ISSUE TITLE
Coins with zero value

### ISSUE THREAD

**Issue by jdmarlow86** [atomiclabs/hyperdex#442]
The COQUI and EQL coins on some occasions show zero price. As of now COQUI updated with a price while EQL remains at zero. Is this because of marketmaker?

Version: alpha 10
OS: win 10
Errors: none
Severity: Medium (2)

![image](https://user-images.githubusercontent.com/22251770/43096354-d695d906-8e86-11e8-872b-10ac1905205f.png)

**Comment by lukechilds** [comment]
If the coin isn't listed on CMC then we get the value in KMD directly from `marketmaker` and multiply it by the CMC KMD/USD price.

I think mm just shows the average of the trades, so if the trading volume is low then maybe it will drop to 0.
