### ISSUE TITLE
Can not trade KMD to GLX.

### ISSUE THREAD

**Issue by VONLUEAPS** [atomiclabs/hyperdex#455]
Steps :
1. Select the coin you want to trade. KMD and GLX.
2. Enter the values [Price GLXT] and [Amount KMD] in the Sell KMD column.
    - Price GLXT : 306.23181105
    - Amount KMD : 4
3. Click the [Sell KMD] button.
4. Wait until the trade is completed.

Fail step is 3 as below image:
![image](https://user-images.githubusercontent.com/16932261/43316362-16c1ec36-91d4-11e8-8dbf-c232cfa8b1aa.png)

But, my [Balance] larger than [Amount KMD]...
![image](https://user-images.githubusercontent.com/16932261/43316392-30b021d0-91d4-11e8-9009-2e70fd51abae.png)

Please check that.
Thanks,
Best regards, VLAPS
---

HyperDEX 0.1.0-alpha.10
Electron 2.0.5
win32 10.0.17134
Locale: ko

**Comment by VONLUEAPS** [comment]
Not all transactions are possible, not just GLX.

**Comment by VONLUEAPS** [comment]
OK. I'm understand.
If I want to trade on HyperDEX, must have 10 or more....

Please pop up message as "Users must have more than 10 KMDs in their exchange wallets to trade" ...

**Comment by lukechilds** [comment]
It's not the balance that's important, it's having correctly sized UTXOs.

You need one UTXO that is equal or larger than the size you want to trade, and another UTXO suitable to be used for the dex fee.

This is how the underlying `marketmaker` daemon works and is something we are unable to resolve from the GUI.

There is an explanation about this in the first run dialog, but you're right, the error should be much more clear. Those errors are passed directly through from `marketmaker` and there are no error codes so there's no reliable way for us to catch them and give users more reliable errors. (see https://github.com/atomiclabs/hyperdex/issues/180 https://github.com/jl777/SuperNET/issues/594 https://github.com/jl777/SuperNET/issues/717)

**Comment by lukechilds** [comment]
I will close this issue as we already have "Better error reporting" tracked here: #180

Thanks for reporting.
