### ISSUE TITLE
Unhandled Promise Rejection Type Error: Cannot read property 'find' of undefined     at messages.forEach.message (app://-/bundle.js:98917:39)     at Array.forEach (<anonymous>)     at _formatSwap (app://-/bundle.js:98873:12)     at Array.map (<anonymous>)     at app://-/bundle.js:99021:20     at Generator.next (<anonymous>)     at step (app://-/bundle.js:98707:191)     at app://-/bundle.js:98707:361     at <anonymous>

### ISSUE THREAD

**Issue by blackzetss** [atomiclabs/hyperdex#456]
---

HyperDEX 0.1.0-alpha.11
Electron 2.0.4
darwin 17.7.0
Locale: uk

**Comment by sindresorhus** [comment]
Please follow the instructions in the release notes: 

> Important: If you have used any previous beta version, you need to delete your trade history as this version has an incompatible format. Right after opening this version, go to the "Debug" menu and choose "Delete Trade History". - https://github.com/atomiclabs/hyperdex/releases/tag/v0.1.0-alpha.11
