### ISSUE TITLE
GET error with coin market cap ticker

### ISSUE THREAD

**Issue by jdmarlow86** [atomiclabs/hyperdex#465]
Getting the below error after load resulting in a $0 value for all coins. Occurs consistenly.

Version: alpha 11
OS: win 10
Errors: below
Severity: High

**GET https://api.coinmarketcap.com/v2/ticker/1392/ 429 ()
-/:1 Failed to load https://api.coinmarketcap.com/v2/ticker/1392/: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'app://-' is therefore not allowed access. The response had HTTP status code 429. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.**

Is this related to https://github.com/atomiclabs/hyperdex/issues/464 ?

**Comment by sindresorhus** [comment]
> Is this related to #464?

Yes, CMC started actively rate-limiting...

**Comment by sindresorhus** [comment]
Closing as we've switch vendor now. See https://github.com/atomiclabs/hyperdex/commit/dbecfaf3ae1efdd621df1536009659a78d77df0e
