### ISSUE TITLE
MYTH coin default

### ISSUE THREAD

**Issue by jdmarlow86** [atomiclabs/hyperdex#469]
Unicoin (MYTH) is not in the default coin list

Version: alpha 11
OS: win 10
Errors: none
Severity: Low

**Comment by sindresorhus** [comment]
It's only added by default for new portfolios. We don't want to mess with people's existing portfolios.

**Comment by jdmarlow86** [comment]
Created a new portfolio and it wasn't there either, it did however copy all the coins from my first portfolio which I don't remember it ever doing

**Comment by sindresorhus** [comment]
Ah yeah, sorry, I meant fresh install. We currently store the enabled coins in the app settings and not the portfolio data. We need to fix that.

**Comment by jdmarlow86** [comment]
Cool, thanks!
