### ISSUE TITLE
GET ticker error

### ISSUE THREAD

**Issue by jdmarlow86** [atomiclabs/hyperdex#473]
Referencing https://github.com/atomiclabs/hyperdex/issues/465

I'm still getting the below ticker error resulting in a holding value of 0 for all coins.

Version: alpha 11
OS: win 10
Errors: below
Severity: High

![image](https://user-images.githubusercontent.com/22251770/44109499-3b5fbfdc-9fcb-11e8-9fc2-5afb92901acd.png)

**Comment by sindresorhus** [comment]
You're not on the latest version: https://github.com/atomiclabs/hyperdex/releases/latest

You have to manually update to new versions.

**Comment by jdmarlow86** [comment]
Apologies, didn't see the update
