### ISSUE TITLE
Error in Exchange view

### ISSUE THREAD

**Issue by jdmarlow86** [atomiclabs/hyperdex#475]
1. Open HDEX and login
2. Select Exchange view
3. Receive the below error

Additional note - after receiving the error I tried to do a BEER/PIZZA swap. The swap never appeared in the Recent Swaps section.

Version: alpha 12
OS: win 10
Errors: below
Severity: High

![image](https://user-images.githubusercontent.com/22251770/44169623-06dc1480-a0a3-11e8-8cee-ad853c7c2160.png)

**Comment by sindresorhus** [comment]
Duplicate of #456
