### ISSUE TITLE
Exchange -Number of swaps update

### ISSUE THREAD

**Issue by jdmarlow86** [atomiclabs/hyperdex#496]
Related to https://github.com/atomiclabs/hyperdex/pull/445 I do not see a "View all swaps" button.

Version: alpha 12
OS: win 10
Errors: none
Severity: low

**Comment by sindresorhus** [comment]
It only shows up at the bottom of the list when you have more than 50 swaps. It doesn't matter though as in the next alpha, which I'm releasing later today, we will no longer limit it as we now only show open orders in the Exchange view. And we'll add an always visible button to view the history (complete/failed swaps): #495 I'll write more about it in the release notes ;)
