### ISSUE TITLE
Swaps stuck 2/5 and 3/5

### ISSUE THREAD

**Issue by ptyx11** [atomiclabs/hyperdex#498]
There seems to be an issue with swaps getting stuck and also not chaging to failed swap or unmatched. 

<img width="420" alt="screen shot 2018-09-01 at 6 24 24 pm" src="https://user-images.githubusercontent.com/32718517/44950706-9e1bc880-ae14-11e8-8598-5de5c1c30fa0.png">

---

HyperDEX 0.1.0-alpha.13
Electron 2.0.8
darwin 17.7.0
Locale: en-US

**Comment by lukechilds** [comment]
This doesn't appear to be an issue, it just seems to be taking a long time to swap. This is unrelated to HyperDEX.

The atomic swap protocol can take hours to complete if one of the parties goes offline and the correct state of the swap is that it is swapping. They shouldn't show as failed or unmatched.

However, I have managed to successfully do a ZILLA/KMD swap which seems to be what you're having issues with:

![screen shot 2018-09-04 at 5 07 47 pm](https://user-images.githubusercontent.com/2123375/45043434-124cab00-b065-11e8-9436-d9faa88add74.png)

https://gist.github.com/lukechilds/0ffbb58416c13bc438ec1f38b652cee4
