### ISSUE TITLE
Cancel swap does not work

### ISSUE THREAD

**Issue by jdmarlow86** [atomiclabs/hyperdex#504]
Created an order -> waited 5 minutes -> selected cancel -> the order remained open

Additional note: The swap would cancel when I close the app but there was only a small time frame that the confirmation window was open.

Version: alpha 13
OS: win 10
Errors: none
Severity: Medium

**Comment by lukechilds** [comment]
Can reproduce this.

@jdmarlow86 The cancel behaviour in `marketmaker` is quite buggy, you can read more on it here:

- https://github.com/jl777/SuperNET/issues/844
- https://github.com/atomiclabs/hyperdex/issues/129
- https://github.com/atomiclabs/hyperdex/issues/262#issuecomment-395390245
- https://github.com/atomiclabs/hyperdex/issues/345

It seems temperamental and normally works, but sometimes it doesn't. We were aware the cancel behaviour was pretty buggy which was why we removed it previously, but we needed to add it back in when adding good 'till cancelled (GTC) orders.

To clarify, the bugginess is in `marketmaker`, not HyperDEX, we don't get reliable information back from the API to know what's happening.

In my reproduction scenario, I get this response from `marketmaker` when cancelling an open order:

```
{"result":"success","numentries":0,"status":"will stop trade negotiation, but if swap started it wont cancel"}
```

Which the UI treats as a cancel being issued so blanks out the cancel button.

However mm never cancels the trade internally so we don't get a cancel update message for the trade over the socket to it remains listed as "open".

The text in the message a little ambigious, it's not clear what "started" means
>will stop trade negotiation, but if swap started it won't cancel

But I can see in my instance there hasn't been any network activity at all, not even any `request` or `reserved` messages, so it would appear this trades hasn't "started" and should definitely of cancelled.

We will likely have to wait for mmv2 for stable cancel functionality.

// cc @jl777 @artemii235 @ArtemGr

**Comment by jorian** [comment]
mm1.0 related
