### ISSUE TITLE
GLXT Server connection

### ISSUE THREAD

**Issue by jdmarlow86** [atomiclabs/hyperdex#505]
On app open I receive a "Could not connect to GLXT Electrum Server" error

Version: alpha 13
OS: win 10
Errors: below
Severity: Medium

![image](https://user-images.githubusercontent.com/22251770/45117429-89487900-b123-11e8-985d-d41f72ee6c09.png)

**Comment by lukechilds** [comment]
Thanks for reporting, this is an issue on the GLXT end though not related to HyperDEX, we use the official GLXT electrum servers:

`electrum1.glx.co`
`electrum2.glx.co`

https://github.com/atomiclabs/hyperdex/blob/4b9d39737a514c0aa11b4d951feb1f9d8d6e96b8/app/marketmaker/supported-currencies.js#L995-L1009

Could you report the issue to GLXT if the issue persists?
