### ISSUE TITLE
Unsupported currency EQL error

### ISSUE THREAD

**Issue by jenbuzz** [atomiclabs/hyperdex#537]
Noticed this error in the console:

![hyperdex-eql](https://user-images.githubusercontent.com/3244222/46210795-06859900-c332-11e8-9357-0245f1213855.png)

EQL => EQLI

Seen in the latest nightly build: v0.0.0-83a598a-18.9.27.1511

**Comment by jdmarlow86** [comment]
Was just about to report this in 0.1.3 👍
