### ISSUE TITLE
First login error

### ISSUE THREAD

**Issue by jdmarlow86** [atomiclabs/hyperdex#547]
**Describe the bug**

On the first login attempt I am consistently receiving the below error. Second login attempt works

**To reproduce**
1. Open HyperDEX
2. Login

**Expected behavior**

Successful login with no errors

**Screenshots**

![Uploading image.png…]()

**System info**

- OS & version: Windows 10
- HyperDEX version: 0.1.4
-Severity: High

**Comment by kevva** [comment]
The screenshot doesn't show.

**Comment by jdmarlow86** [comment]
Issue no longer exists in v0.2.0 - is ok to close
