### ISSUE TITLE
Get back money from failed trade

### ISSUE THREAD

**Issue by bucksnort70** [atomiclabs/hyperdex#554]
hi, figured I'd try some trading on hyperdex with small amount of KMD.  A swap for VRSC failed.  ID: 112ad1999eeb36cc620ac5d0d35a0c870c758a49610799ae28c8fdb3265f60bc Got error code -1007 Took my KMD, but no VRSC in return.  TXID: fbdea6c1e2f44e1e3544d4f2115e500fe3b0eac4cb4dc6f4b5a68fa389c5091c  If I lost it, not the end of the world, I knew the risk.  Just wondering if there is a way to get it back?

---

HyperDEX 0.1.4
Electron 3.0.0
win32 10.0.17134
Locale: en-US

**Comment by bucksnort70** [comment]
![screenshot 5](https://user-images.githubusercontent.com/44144704/46921307-6a10f700-cfbf-11e8-955b-613bcd3a4322.png)

**Comment by sindresorhus** [comment]
Your funds are most likely not lost. See: https://github.com/atomiclabs/hyperdex/issues/536

**Comment by bucksnort70** [comment]
Got it back!!

Problem
Swap is stuck at some stage and showing pending.
I didn't receive my alice payment back.
I didn't receive bob payment.

Solution
This can happen for multiple reasons. Don't panic! Funds are secure and you can get funds back depending on which stage the swap was. All you need is UUID of the stuck swap.
Wait for minimum 4 hours after your swap is stuck. Then, follow the steps below:
Stop HyperDEX
Start HyperDEX
Login using the same passphrase
Go to the exchange page of the stuck swap (i.e.: BTC/KMD exchange page)
Enter the following in the debug console using UUID from the stuck swap and hit Enter button in your keyboard and wait few minutes
We used f8b3d902d9c21ed0a2231ade8965f6f710d04953c27f00156e9a346550de1b20 as example UUID
_swapDB._getSwapData('f8b3d902d9c21ed0a2231ade8965f6f710d04953c27f00156e9a346550de1b20').then(data => data.messages.reduce((ids, msg) => {ids.requestid = msg.requestid || ids.requestid;ids.quoteid = msg.quoteid || ids.quoteid;return ids;}, {})).then(ids => {console.log(ids);_api.debug({method: 'kickstart', ...ids});});

**Comment by lukechilds** [comment]
@bucksnort70 thanks for updating.
