### ISSUE TITLE
Seed format compatibility

### ISSUE THREAD

**Issue by nickname371** [atomiclabs/hyperdex#556]
I am trying to recover portfolio with seed from Agama and Ethereum wallet but HyperDex shows zero balance despite I see it in those wallets.
Is there something different seeds format with "portfolio" wallet in HyperDex?

**Comment by lukechilds** [comment]
HyperDEX uses the same key derivation algorithm as Agama. It probably doesn't use the same algorithm as your Ethereum wallet, you should send the funds over instead.
