### ISSUE TITLE
QMC electrum server not connecting

### ISSUE THREAD

**Issue by jdmarlow86** [atomiclabs/hyperdex#559]
**Describe the bug**
I am receiving a "Could not connect to QMC server" error on login after adding QMC

**To reproduce**
1. Open HyperDEX
2. Add QMC in Settings view
3. Close app
4. Open app
5. Login to portfolio 

**Expected behavior**
Successful login with no errors

**Screenshots**

![image](https://user-images.githubusercontent.com/22251770/47457331-ca185200-d7a4-11e8-90ce-8f23516a1854.png)

**System info**

- OS & version: Windows 10
- HyperDEX version: 0.2.0

**Comment by sindresorhus** [comment]
I'm also able to successfully connect to the QMC Electrum server.

**Comment by jdmarlow86** [comment]
Just tried again and couldn't connect

![image](https://user-images.githubusercontent.com/22251770/47660782-221cd300-db6e-11e8-869f-0616ba07d184.png)

**Comment by sindresorhus** [comment]
// @project-qmc
