### ISSUE TITLE
Dashboard view chart disappears

### ISSUE THREAD

**Issue by jdmarlow86** [atomiclabs/hyperdex#572]
**Describe the bug**
The chart filters disappear after selecting the All option in the Dashboard view

**To reproduce**
1. Login to app
2. With Dashboard open select a coin with valid chart data
3. Select the All chart view in the top right corner

**Expected behavior**
After selecting the All Chart view I should see the entire timeline of the coin

**Screenshots**
Before
![image](https://user-images.githubusercontent.com/22251770/48652423-72e55600-e9cd-11e8-877b-e09069f38c3d.png)
After
![image](https://user-images.githubusercontent.com/22251770/48652434-7d075480-e9cd-11e8-8c02-5b4f11d83c3e.png)

**System info**

- OS & version: Windows 10
- HyperDEX version: 0.2.1

**Comment by osyed** [comment]
I noticed the same problem. Had to restart the program to get it back.
