### ISSUE TITLE
Error sending to zaddress

### ISSUE THREAD

**Issue by jdmarlow86** [atomiclabs/hyperdex#582]
**Describe the bug**

I receive the below error when attempting to send BEER to the following z sapling address

zs1g80ekk4cezjamhcgqfvz2zjv3d5u0tqh34zrfa6pqfk4tpkqhm739j9r40x5c8krk3dxxsdh7hc

**To reproduce**
1. Login
2. On Dashboard select BEER
3. Select Withdraw
4. Enter above address then select Withdraw
-->

**Expected behavior**

Withdraw is executed with no errors

**Screenshots**

![image](https://user-images.githubusercontent.com/22251770/50190274-a716a400-02f6-11e9-8620-ff3243c3026c.png)

**System info**

- OS & version: Windows 10
- HyperDEX version: 0.3.0

**Additional context**

Error:
Unhandled Promise Rejection
Error: Couldn't create withdrawal transaction:
{ txid:
   '0000000000000000000000000000000000000000000000000000000000000000',
  txfee: 1000,
  complete: false }
    at errorWithObject (app://-/bundle.js:106021:46)
    at Api._createTransaction (app://-/bundle.js:106278:13)

**Comment by lukechilds** [comment]
This is expected, shielded addresses aren't supported.
