### ISSUE TITLE
Add PGT logo to Hyperdex

### ISSUE THREAD

**Issue by pungotoken** [atomiclabs/hyperdex#586]
**Describe the bug**

Default logo appearing

**To reproduce**

1. Go to PGT
2. Default logo appears

**Expected behavior**

Add PGT logo here https://github.com/jl777/coins/blob/master/icons/pgt.png

**Additional context**
Resources: https://github.com/jl777/coins/blob/master/icons/pgt.png

**Comment by sindresorhus** [comment]
It's already added in `master` branch and will be available in the next release. If you don't want to wait, you can try out the latest [nightly release](https://github.com/atomiclabs/hyperdex-nightlies/releases/latest).

<img width="1172" alt="screen shot 2018-12-29 at 22 18 42" src="https://user-images.githubusercontent.com/170270/50542193-d4e1cf80-0bb7-11e9-9e27-46f9dcffe251.png">
