### ISSUE TITLE
I mistakenly saved ETH in this wallet? how will i withdraw?

### ISSUE THREAD

**Issue by iamahmedshah** [atomiclabs/hyperdex#596]
---

HyperDEX 0.4.0
Electron 4.0.1
darwin 17.0.0
Locale: en-US

**Comment by lukechilds** [comment]
Is the normal withdraw function not working?

**Comment by iamahmedshah** [comment]
yes it is not working and is stucked on this.

**Comment by iamahmedshah** [comment]
I imported ETH into Agama with the same seed , I was reviewing Hyper DEX
but mistakenly put some ETH, but cool got it figured you should work on
updates I know it sucks i also got a project to make mobile wallet for a
crypto but dont even know where to start and what API to use for sending
and receiving
