### ISSUE TITLE
Use the new `elementType` PropType

### ISSUE THREAD

**Issue by sindresorhus** [atomiclabs/hyperdex#598]
See https://github.com/facebook/prop-types/pull/211

We should use it instead of `PropType.func` in most places, except for change handlers.

**Comment by ru-lai** [comment]
@sindresorhus I'd like to work on this issue.
I'll get started and make a pr when ready.

**Comment by ru-lai** [comment]
PR https://github.com/atomiclabs/hyperdex/pull/600 should solve this issue.
