### ISSUE TITLE
HUSH3

### ISSUE THREAD

**Issue by Micah68** [atomiclabs/hyperdex#601]
Hello,
I just downloaded and created a hypedex account for the purpose of exchanging HUSH with other coins. When will hyperdex be compatible with the HUSH3 network? Currently hyperdex has the "t" wallet addresses and I was hoping to see the "R" addresses.
Thanks!
E.F. 

We appreciate your feedback!
Try to include as much relevant info as possible.

Security issues should be reported to hyperdex@protonmail.com, **not** on GitHub.

-->

---

HyperDEX 0.4.0
Electron 4.0.1
win32 10.0.17763
Locale: en-US

**Comment by jorian** [comment]
HUSH3 has been updated in HyperDEX per https://github.com/atomiclabs/hyperdex/pull/623/commits/c6c5ef53b19d81000115bfb2f1716da9d0cd6ac7
