### ISSUE TITLE
DEX balance not visible 

### ISSUE THREAD

**Issue by breadmando** [atomiclabs/hyperdex#613]
**DEX balance dose not show up despite restarting**

- OS & version: apple dmg 
- HyperDEX version: hyperdex-nightlies 0.0.0-c2d7531-19.7.28.1746

**Comment by sindresorhus** [comment]
This sounds like a mm2 problem. HyperDEX just displays the balance it gets from mm2. Can you double-check that you actually have something on that address? Many coins are not yet tested with mm2, so it might not be compatible yet.

**Comment by breadmando** [comment]
ok

**Comment by breadmando** [comment]
ok checked again it now working.
not sure why that was previously. 

I will close the issue now thanks
